server:
  port: 8088
spring:
  application:
    name: cart-service
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
      #注册表取值间隔
    registry-fetch-interval-seconds: 10
  #实例
  instance:
    #地址
    ip-address: 127.0.0.1
    #显示ip地址
    prefer-ip-address: true
    instance-id: ${eureka.instance.ip-address}.${sever.port}
    #租约更新间隔(以秒为单位)
    lease-renewal-interval-in-seconds: 5
    #租约过期持续时间(以秒为单位)
    lease-expiration-duration-in-seconds: 15
leyou:
  jwt:
    pubKeyPath: F:\\tmp\\rsa\\rsa.pub # 公钥地址
    cookieName: LY_TOKEN